openfisca/openfisca-web-api

- .travis.yml
- Makefile
- Improve `make flake8` performance.
- Prefer harnessing information rather than shortening feedback time when in CI.
> Improve makefile

- openfisca_web_api/controllers/common.py
- openfisca_web_api/controllers/fields.py
- openfisca_web_api/controllers/formula.py
- openfisca_web_api/controllers/swagger.py
Ease working around openfisca/openfisca-core#329.
> Factor output/input formula detection

- openfisca_web_api/controllers/formula.py
- openfisca_web_api/controllers/swagger.py
- openfisca_web_api/tests/test_swagger.py
- openfisca_web_api/wsgihelpers.py
- Update basePath.
- Add global documentation.
- Document response schemas.
- Document period parameter.
> Update /swagger to document /2/formula

- openfisca_web_api/tests/test_formula_2.py
- openfisca_web_api/wsgihelpers.py
> Support dates in JSON output

- openfisca_web_api/controllers/calculate.py
- openfisca_web_api/controllers/formula.py
Interdependent with https://github.com/openfisca/openfisca-core/pull/379
> Adapt to extra_params core branch

- openfisca_web_api/controllers/formula.py
Avoid creating a simulation for each formula in a request
> Cache simulation in /formula

- CHANGELOG.md
- development-france.ini
- openfisca_web_api/controllers/parameters.py
- openfisca_web_api/controllers/reforms.py
- openfisca_web_api/conv.py
- openfisca_web_api/environment.py
- openfisca_web_api/model.py
- openfisca_web_api/tests/test_calculate.py
- setup.py
- test.ini
* Apply core API changes introduced by [openfisca-core 2.0](https://github.com/openfisca/openfisca-core/pull/388)
> Adapt API to Openfisca 2.0

- CHANGELOG.md
- README.md
- setup.py
The previous organisation is down
> Change pastescript conda install instruction

- travis-run-tests.sh
Connected to #94 
I think we should merge this PR without releasing, by exceptionally un-protecting the `master` branch.
> Check versioning only if code has been updated

- CHANGELOG.md
- README.md
- production-config/README.md
- production-config/config.ini
- production-config/openfisca-web-api.conf
- production-config/openfisca-web-api.service
- setup.py
Connected to #82.
CC @pndsagora
> Update production deployment config

- CHANGELOG.md
- openfisca_web_api/controllers/__init__.py
- openfisca_web_api/controllers/entities.py
- setup.py
Depends on with https://github.com/openfisca/openfisca-core/pull/425
> Use Entity.to_json method of Core

- CHANGELOG.md
- openfisca_web_api/controllers/calculate.py
- openfisca_web_api/controllers/formula.py
- openfisca_web_api/controllers/simulate.py
- openfisca_web_api/conv.py
- openfisca_web_api/tests/test_formula_1.py
- openfisca_web_api/tests/test_formula_2.py
- openfisca_web_api/wsgihelpers.py
- setup.py
Connected to openfisca/openfisca-core#398
> Improve errors for non-existing variables

- CONTRIBUTING.md
- README.md
Connected to openfisca/openfisca-core#471
> Remove "/en" from URL

- openfisca_web_api/model.py
- setup.py
- tests/test_api.py
- tests/test_helpers.py
- tests/tests.py
Depends on #114
Connected to #107 
This is an implementation of proposition 5.
> I'm opening the PR on the `gunicorn` branch to make the review easy, we should edit the destination branch once #114 is merged
> Handle marginal scales parameters

- Makefile
- openfisca_web_api/app.py
- openfisca_web_api/loader/__init__.py
- openfisca_web_api/loader/commons.py
- openfisca_web_api/loader/parameters.py
- openfisca_web_api/loader/tax_benefit_system.py
- openfisca_web_api/loader/variables.py
- openfisca_web_api/model.py
- setup.cfg
- setup.py
- tests/__init__.py
- tests/test_headers.py
- tests/test_helpers.py
- tests/test_parameters.py
- tests/test_variables.py
Connected to #125 
Depends on https://github.com/openfisca/openfisca-dummy-country/pull/6
Depends on https://github.com/openfisca/openfisca-core/pull/494
> Add variables to the new API

- openfisca_web_api/loader/__init__.py
- openfisca_web_api/loader/commons.py
- openfisca_web_api/loader/parameters.py
- openfisca_web_api/loader/variables.py
- setup.py
- tests/test_helpers.py
- tests/test_parameters.py
Connected to openfisca/openfisca-core#437
> Remove fuzzy

- development-france.ini
- development-tunisia.ini
- production-config/config.ini
- setup.py
- test.ini
> Add day to logs

- CHANGELOG.md
- openfisca_web_api/environment.py
- setup.py
Some code was only executed in prod and non tested.
> Fixup #142

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Connected to openfisca/openfisca-doc#89
> Reference the new address of the documentation

- .travis.yml
- CHANGELOG.md
- openfisca_web_api/controllers/calculate.py
- openfisca_web_api/controllers/field.py
- openfisca_web_api/controllers/formula.py
- openfisca_web_api/controllers/swagger.py
- openfisca_web_api/controllers/variables.py
- openfisca_web_api/conv.py
- openfisca_web_api/tests/test_swagger.py
- setup.py
Connected to openfisca/openfisca-core#590
> Adapt Web API to Core v20

- .travis.yml
- CHANGELOG.md
- openfisca_web_api/controllers/swagger.py
- openfisca_web_api/controllers/variables.py
- openfisca_web_api/tests/test_calculate.py
- openfisca_web_api/tests/test_swagger.py
- openfisca_web_api/wsgihelpers.py
- setup.py
Connected to openfisca/openfisca-france#831
> Adapt to Core v21
