development-france.ini
setup.py

See #7 (this won't fix the installation though, there are other unmatchable dependencies).
Another way of correcting the problem would be to allow the dependency to be matched by adding [installation instructions](http://www.openfisca.fr/installation) or, better, automate install.

Remove unmatchable dependency

---

openfisca_web_api/controllers/formula.py
openfisca_web_api/tests/test_calculate.py
openfisca_web_api/tests/test_formula.py
openfisca_web_api/tests/test_graph.py
openfisca_web_api/tests/test_simulate.py
openfisca_web_api/tests/test_swagger.py

- Cover `/formula` endpoint with tests.
- Refactor `/formula`.
- Fix some bugs in `/formula`.
- Return proper HTTP status codes for various errors in `/formula`.
- Mark failing tests in other APIs as pending.

Test /formula

---

openfisca_web_api/controllers/formula.py
openfisca_web_api/tests/test_formula_2.py

[Reference](https://github.com/openfisca/openfisca-core/issues/329#issuecomment-87776913).
Brings back support for `allegement_fillon`.

Update input variable detection in /formula

---

openfisca_web_api/controllers/formula.py

Rather than a plaintext `Internal Server Error`.
See #24 for why it is not in the main responder.

Return a proper JSON 500 in unexpected /formula failure

---

openfisca_web_api/controllers/formula.py
openfisca_web_api/tests/test_formula_2.py

Keep assumption of “one month computation”, but set data for the full year.

Allow computing year-dependent formulas in /formula

---

development-france.ini
openfisca_web_api/controllers/formula.py
openfisca_web_api/model.py

Enable the use of reforms in the /formula endpoint
To keep this endpoint URL simple, they are requested as a list in a custom HTTP header.
```
X-OpenFisca-Extensions: de_net_a_brut, landais_piketty_saez
```
This header is of course optional.

Reforms in formula endpoint

---

CHANGELOG.md
openfisca_web_api/application.py
openfisca_web_api/controllers/parameters.py
openfisca_web_api/controllers/variables.py
openfisca_web_api/environment.py
setup.cfg
setup.py

As it prevents the api from working out of a git repository.
Use the country package version instead, now that we have strict versioning.
Fixes the build.

Don't use git sha

---

CHANGELOG.md
openfisca_web_api/scripts/serve.py
openfisca_web_api/tests/test-cli.sh
run-travis-tests.sh
setup.py

We can now use:
```
$ openfisca-serve
16:29:48,884 INFO  [root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
16:29:48,920 INFO  [root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Serving on http://localhost:2000/
```
to start the Web API.

Add openfisca-serve CLI script

---

CHANGELOG.md
development-france.ini
openfisca_web_api/environment.py
openfisca_web_api/model.py
setup.py

Declare extensions to load in an openfisca instance in the api config file.
Depends on https://github.com/openfisca/openfisca-parsers/pull/17
Depends on https://github.com/openfisca/openfisca-core/pull/399

Add extension loading in api

---

CHANGELOG.md
run-travis-tests.sh
setup.py

The checkout system is causing trouble on builds following a tag release, which prevent automatic pip publication. 
This is a quick fix, but we should consider removing the whole system as we can have something more robust using just version numbers.

Fix run-travis-tests.sh to repair automatic pypi releasing

---

CHANGELOG.md
openfisca_web_api/environment.py
openfisca_web_api/tests/test_variables.py
setup.py

In some cases in `/variables` endpoint, `source_file_path` of each variable was wrong if application was deployed in a virtualenv. This fix uses `importlib` to get the path of the country package instead of `pkg_resources`.

Fix venv wrong path

---

CHANGELOG.md
openfisca_web_api/application.py
openfisca_web_api/environment.py
openfisca_web_api/tests/test_variables.py
setup.py

This fixes a case where email errors were sent but `application/json` content-type was not set.
This changes nothing for the caller.

Refactor middlewares

---

CHANGELOG.md
openfisca_web_api/controllers/__init__.py
openfisca_web_api/controllers/calculate.py
openfisca_web_api/controllers/entities.py
openfisca_web_api/controllers/field.py
openfisca_web_api/controllers/fields.py
openfisca_web_api/controllers/formula.py
openfisca_web_api/tests/test_entities.py
setup.py

The only breaking change is on route `/entities/`, but I don't know in which context this route was used.
```JSON
{
"apiVersion": 1,
"entities": {
"familles": {
"labelByRoleKey": {
"parents": "Parents",
"enfants": "Enfants"
},
"maxCardinalityByRoleKey": {
"parents": 2
},
"roles": ["parents", "enfants"],
"label": "Famille"
},
"foyers_fiscaux": {
"labelByRoleKey": {
"personnes_a_charge": "Personnes à charge",
"declarants": "Déclarants"
},
"maxCardinalityByRoleKey": {
"declarants": 2
},
"roles": ["declarants", "personnes_a_charge"],
"label": "Déclaration d'impôt"
},
"individus": {
"isPersonsEntity": true,
"label": "Personne"
},
"menages": {
"labelByRoleKey": {
"conjoint": "Conjoint",
"autres": "Autres",
"enfants": "Enfants",
"personne_de_reference": "Personne de référence"
}, …
```

Adat web-api to core#v4

---

CHANGELOG.md
examples/calculate_single_person_1.json
examples/calculate_single_person_2.json
openfisca_web_api/controllers/field.py
openfisca_web_api/controllers/graph.py
openfisca_web_api/tests/test_calculate.py
openfisca_web_api/tests/test_swagger.py
setup.py

Comes before #91 
A few variables are hard-coded in tests, and I'm pretty sure that's the only reason for having an explicit dependency constraint to France.
Then we'll be able to merge #91 because it needs on OpenFisca-France == 13.y.z.

Rename variables to follow France evolutions

---

CHANGELOG.md
openfisca_web_api/controllers/simulate.py
openfisca_web_api/environment.py
openfisca_web_api/model.py
setup.py

Connected to #76.
Replaces #81 
Due to openfisca/openfisca-core#450, any `TaxBenefitSystem` has a `decomposition_file_path` attribute.
Comes after #92 because this PR needs OpenFisca-France >= 13.y.z.

Fix the condition to detect if the country package has decompositions

---

CHANGELOG.md
openfisca_web_api/environment.py
setup.py

Bugfix: in development mode (with `paster serve`), fix the path of the country package.
This impacts the `parameters` endpoint.
Before:
```json
{"xml_file_path": "penfisca/openfisca_france/parameters/__root__.xml"}
```
`xml_file_path` is intended to be relative of the directory of the Python package (ie `/home/.../openfisca-france/openfisca_france`).
Its value should be:
```json
{"xml_file_path": "parameters/__root__.xml"}
```
This is the fix: getting the absolute path of the country package directory helps finding the relative path of the XML file (which is an absolute path).

Fix country path in development mode

---

CHANGELOG.md
openfisca_web_api/scripts/serve.py
setup.py

* Make the script `openfisca-serve` work with any country
- Before, it was always loading `openfisca-france`
- Now, the country package (as well as reforms and extensions) can be provided through arguments
- If no country package is provided, an auto-detection is attempted
For more information about how to use the script, run `openfisca-serve -h`.
--------
Usage :
```sh
openfisca-serve # will attempt an auto detection of the country package
openfisca-serve -c openfisca_senegal -p 14000
openfisca-serve -e openfisca_paris -r openfisca_france.reforms.aides_cd93.aides_cd93
```
--------------
Todo : 
- - - -
Fixes #80.

Internationalise openfisca-serve script

---

README.md
circle.yml
openfisca_web_api/server.py
prod/deploy.sh
prod/openfisca-web-api.service
setup.py

Connected to #106 
Once merged:

Deploy API continuously

---

.travis.yml
setup.py

Move flake8 to setup.py "test" extra require.
The reason is to be consistent with https://github.com/openfisca/openfisca-france/pull/713

Clean Continuous Integration config

---

CHANGELOG.md
openfisca_web_api/controllers/calculate.py
openfisca_web_api/controllers/simulate.py
openfisca_web_api/tests/test_calculate.py
openfisca_web_api/tests/test_simulate.py
openfisca_web_api/wsgihelpers.py
setup.py

Connected to #110 
Follows https://github.com/openfisca/openfisca-core/pull/486
`Scenario.new_simulation` can raise `ValueError` corresponding to period mismatch.
This PR catches and returns them to the client in JSON.
This introduces catch-all `try/except` but we agree it's not a problem (see discussion from [this comment](https://github.com/openfisca/openfisca-web-api/issues/110#issuecomment-288719195)).
---
EDIT:
Error received by the client before PR:
```json
{
"error": {
"message": "An internal server error occurred",
"code": 500,
"hint": "See the HTTP server log to see the exception traceback."
}
}
```
Error received by the client after PR:
```json
{
"error": {
"message": "ValueError: Unable to set a value for variable enfant_a_charge for month-long period 2017-02. enfant_a_charge …
```

Handle errors in calculate and simulate endpoints

---

prod/deploy.sh

Connected to openfisca/openfisca-ops#4
Install requirements from openfisca-ops in order to use the same version of France than the legacy web API.

Install requirements from ops

---

prod/openfisca-web-api.service

It must not be the same than the legacy API one

Update service description

---

.travis.yml
setup.py

Connected to openfisca/openfisca-core#500
Parsers are now deprecated and not referenced in core anymore

Adapt web API to Core v16

---

README.md

Connected to openfisca/openfisca-core#577
Add deprecation information to README.
Explain deprecation main reasons and add link to new API.

Deprecate openfisca-web-api package
